
import os
import psycopg2
import requests
from pathlib import Path
from dotenv import load_dotenv

# Force load the .env file dynamically targeting the root folder
BASE_DIR = Path(__file__).resolve().parent.parent.parent
dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=dotenv_path)

print(f"[DEBUG] Looking for .env at: {dotenv_path}")
print(f"[DEBUG] DB_NAME loaded: {os.getenv('DB_NAME')}")
print(f"[DEBUG] DB_PASSWORD loaded: {'***' if os.getenv('DB_PASSWORD') else 'None'}")

def get_db_connection():
    """Connect to the PostgreSQL database."""
    return psycopg2.connect(
        host="localhost",
        port=5432,
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
    )

def query_aqi_data(grid_id, lookback_hours=72):
    """Fetch current metrics and future XGBoost predictions for the target grid cell."""
    conn = get_db_connection()
    cur = conn.cursor()

    # 1. Get the latest live metrics snapshot
    live_query = """
    SELECT gf.pm25, gf.pm10, gf.no2, gf.co, gf.so2, gf.o3, gf.aqi, gf.timestamp
    FROM grid_features gf
    WHERE gf.grid_id = %s AND gf.timestamp >= NOW() - INTERVAL '%s hours'
    ORDER BY gf.timestamp DESC LIMIT 1;
    """
    cur.execute(live_query, (grid_id, lookback_hours))
    live_row = cur.fetchone()
    
    # 2. Get the future AI forecasts generated by your XGBoost script
    forecast_query = """
    SELECT target_timestamp, predicted_aqi, source_attribution, confidence_score
    FROM ai_predictions
    WHERE grid_id = %s AND target_timestamp > NOW()
    ORDER BY target_timestamp ASC LIMIT 3;
    """
    cur.execute(forecast_query, (grid_id,))
    forecast_rows = cur.fetchall()
    
    cur.close()
    conn.close()

    if not live_row:
        return {}

    # Pack both sets of data into a single context dictionary
    result = {
        "pm25": live_row[0], "pm10": live_row[1], "no2": live_row[2],
        "co": live_row[3], "so2": live_row[4], "o3": live_row[5],
        "aqi": live_row[6], "timestamp": live_row[7],
        "forecasts": []
    }
    
    for row in forecast_rows:
        result["forecasts"].append({
            "time": row[0],
            "aqi": row[1],
            "attribution": row[2], # Already a dictionary/json from your script
            "confidence": row[3]
        })
        
    return result

def format_data_context(data):
    """Format both live metrics and future ML predictions as a text context block."""
    if not data:
        return "No telemetry or predictive metrics available for this sector."

    lines = ["=== CURRENT REAL-TIME SNAPSHOT ==="]
    lines.append(f"Current Measured AQI: {data['aqi']:.1f}")
    lines.append(f"PM2.5: {data['pm25']:.1f} ug/m3 | PM10: {data['pm10']:.1f} ug/m3")
    lines.append(f"NO2: {data['no2']:.1f} ug/m3 | CO: {data['co']:.1f} mg/m3")
    
    if data.get("forecasts"):
        lines.append("\n=== FUTURE FORECASTS (GENERATED VIA XGBOOST MACHINE LEARNING) ===")
        for f in data["forecasts"]:
            time_str = f["time"].strftime("%Y-%m-%d %H:%M")
            lines.append(f"• Target Time: {time_str}")
            lines.append(f"  Predicted AQI: {f['aqi']} (Model Confidence: {f['confidence']*100:.0f}%)")
            if f["attribution"]:
                attr = f["attribution"]
                lines.append(f"  Source Risk: Traffic: {attr.get('traffic')}% | Industrial: {attr.get('industrial')}% | Crop Burning: {attr.get('crop_burning')}%")
                
    return "\n".join(lines)

def generate_llm_response_ollama(user_query, grid_id):
    """Generate response using Ollama local serving layer."""
    data = query_aqi_data(grid_id)
    
    # Fallback backup sequence in case target grid has no entries yet
    if not data:
        print("[INFO] Target grid context empty. Fetching latest available grid metrics block...")
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("SELECT grid_id FROM grid_features ORDER BY timestamp DESC LIMIT 1;")
        row = cur.fetchone()
        cur.close()
        conn.close()
        if row:
            grid_id = row[0]
            data = query_aqi_data(grid_id)

    context = format_data_context(data)

    system_prompt = f"""You are an urban air quality assistant chatbot.
[GROUNDING TELEMETRY DATA]
{context}

INSTRUCTION: Answer the user's inquiry using only the grounding telemetry data provided above. Speak in plain, conversational English. Do not formulate metrics or assume values not explicitly listed."""

    try:
        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": "mistral",
                "prompt": f"{system_prompt}\n\nUser Question: {user_query}\nChatbot Answer:",
                "stream": False,
                "options": {"temperature": 0.2}
            },
            timeout=45
        )
        response.raise_for_status()
        return response.json().get("response", "Error: Model returned an empty response slice.").strip()
    except requests.exceptions.ConnectionError:
        return "Error: Ollama background engine is not responding. Please check if 'ollama serve' is running."
    except Exception as e:
        return f"Pipeline Error: {str(e)}"

def generate_llm_response(user_query, grid_id, provider="ollama"):
    if provider == "ollama":
        return generate_llm_response_ollama(user_query, grid_id)
    return f"Unsupported engine configuration: {provider}"

if __name__ == "__main__":
    # Test using your real database entries discovered during the SQL audit
    test_grid = "grid_2_2" 
    test_query = "What is the current air quality right now, and what does our machine learning model predict will happen over the next 3 days? Are there any specific risk factors?"
    
    print("\n" + "="*60)
    print(f"Firing Grounded Local RAG Execution Loop for {test_grid}...")
    print("="*60)
    
    answer = generate_llm_response(test_query, test_grid, provider="ollama")
    print(f"\nUser: {test_query}")
    print(f"Bot: {answer}\n")
=======
    import os
    import psycopg2
    import requests
    from pathlib import Path
    from dotenv import load_dotenv

    # Force load the .env file dynamically targeting the root folder
    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    dotenv_path = BASE_DIR / ".env"
    load_dotenv(dotenv_path=dotenv_path)

    print(f"[DEBUG] Looking for .env at: {dotenv_path}")
    print(f"[DEBUG] DB_NAME loaded: {os.getenv('DB_NAME')}")
    print(f"[DEBUG] DB_PASSWORD loaded: {'***' if os.getenv('DB_PASSWORD') else 'None'}")

    def get_db_connection():
        """Connect to the PostgreSQL database."""
        return psycopg2.connect(
            host="localhost",
            port=5432,
            dbname=os.getenv("DB_NAME"),
            user=os.getenv("DB_USER"),
            password=os.getenv("DB_PASSWORD"),
        )

    def query_aqi_data(grid_id, lookback_hours=72):
        """Fetch current metrics and future XGBoost predictions for the target grid cell."""
        conn = get_db_connection()
        cur = conn.cursor()

        # 1. Get the latest live metrics snapshot
        live_query = """
        SELECT gf.pm25, gf.pm10, gf.no2, gf.co, gf.so2, gf.o3, gf.aqi, gf.timestamp
        FROM grid_features gf
        WHERE gf.grid_id = %s AND gf.timestamp >= NOW() - INTERVAL '%s hours'
        ORDER BY gf.timestamp DESC LIMIT 1;
        """
        cur.execute(live_query, (grid_id, lookback_hours))
        live_row = cur.fetchone()
        
        # 2. Get the future AI forecasts generated by your XGBoost script
        forecast_query = """
        SELECT target_timestamp, predicted_aqi, source_attribution, confidence_score
        FROM ai_predictions
        WHERE grid_id = %s AND target_timestamp > NOW()
        ORDER BY target_timestamp ASC LIMIT 3;
        """
        cur.execute(forecast_query, (grid_id,))
        forecast_rows = cur.fetchall()
        
        cur.close()
        conn.close()

        if not live_row:
            return {}

        # Pack both sets of data into a single context dictionary
        result = {
            "pm25": live_row[0], "pm10": live_row[1], "no2": live_row[2],
            "co": live_row[3], "so2": live_row[4], "o3": live_row[5],
            "aqi": live_row[6], "timestamp": live_row[7],
            "forecasts": []
        }
        
        for row in forecast_rows:
            result["forecasts"].append({
                "time": row[0],
                "aqi": row[1],
                "attribution": row[2], # Already a dictionary/json from your script
                "confidence": row[3]
            })
            
        return result

    def format_data_context(data):
        """Format both live metrics and future ML predictions as a text context block."""
        if not data:
            return "No telemetry or predictive metrics available for this sector."

        lines = ["=== CURRENT REAL-TIME SNAPSHOT ==="]
        lines.append(f"Current Measured AQI: {data['aqi']:.1f}")
        lines.append(f"PM2.5: {data['pm25']:.1f} ug/m3 | PM10: {data['pm10']:.1f} ug/m3")
        lines.append(f"NO2: {data['no2']:.1f} ug/m3 | CO: {data['co']:.1f} mg/m3")
        
        if data.get("forecasts"):
            lines.append("\n=== FUTURE FORECASTS (GENERATED VIA XGBOOST MACHINE LEARNING) ===")
            for f in data["forecasts"]:
                time_str = f["time"].strftime("%Y-%m-%d %H:%M")
                lines.append(f"• Target Time: {time_str}")
                lines.append(f"  Predicted AQI: {f['aqi']} (Model Confidence: {f['confidence']*100:.0f}%)")
                if f["attribution"]:
                    attr = f["attribution"]
                    lines.append(f"  Source Risk: Traffic: {attr.get('traffic')}% | Industrial: {attr.get('industrial')}% | Crop Burning: {attr.get('crop_burning')}%")
                    
        return "\n".join(lines)

    def generate_llm_response_ollama(user_query, grid_id):
        """Generate response using Ollama local serving layer."""
        data = query_aqi_data(grid_id)
        
        # Fallback backup sequence in case target grid has no entries yet
        if not data:
            print("[INFO] Target grid context empty. Fetching latest available grid metrics block...")
            conn = get_db_connection()
            cur = conn.cursor()
            cur.execute("SELECT grid_id FROM grid_features ORDER BY timestamp DESC LIMIT 1;")
            row = cur.fetchone()
            cur.close()
            conn.close()
            if row:
                grid_id = row[0]
                data = query_aqi_data(grid_id)

        context = format_data_context(data)

        system_prompt = f"""You are an urban air quality assistant chatbot.
    [GROUNDING TELEMETRY DATA]
    {context}

    INSTRUCTION: Answer the user's inquiry using only the grounding telemetry data provided above. Speak in plain, conversational English. Do not formulate metrics or assume values not explicitly listed."""

        try:
            response = requests.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": "mistral",
                    "prompt": f"{system_prompt}\n\nUser Question: {user_query}\nChatbot Answer:",
                    "stream": False,
                    "options": {"temperature": 0.2}
                },
                timeout=45
            )
            response.raise_for_status()
            return response.json().get("response", "Error: Model returned an empty response slice.").strip()
        except requests.exceptions.ConnectionError:
            return "Error: Ollama background engine is not responding. Please check if 'ollama serve' is running."
        except Exception as e:
            return f"Pipeline Error: {str(e)}"

    def generate_llm_response(user_query, grid_id, provider="ollama"):
        if provider == "ollama":
            return generate_llm_response_ollama(user_query, grid_id)
        return f"Unsupported engine configuration: {provider}"

    if __name__ == "__main__":
        # Test using your real database entries discovered during the SQL audit
        test_grid = "grid_2_2" 
        test_query = "What is the current air quality right now, and what does our machine learning model predict will happen over the next 3 days? Are there any specific risk factors?"
        
        print("\n" + "="*60)
        print(f"Firing Grounded Local RAG Execution Loop for {test_grid}...")
        print("="*60)
        
        answer = generate_llm_response(test_query, test_grid, provider="ollama")
        print(f"\nUser: {test_query}")
        print(f"Bot: {answer}\n")

